# Generated by Django 6.0.5 on 2026-05-18 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Autori',
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zanr', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Žanrovi',
            },
        ),
        migrations.CreateModel(
            name='Knjiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('godina', models.IntegerField()),
                ('kolicina', models.IntegerField(default=0)),
                ('puta_posudjena', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knjiznica.autor')),
                ('zanr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knjiznica.zanr')),
            ],
            options={
                'verbose_name_plural': 'Knjige',
            },
        ),
        migrations.CreateModel(
            name='Posudba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_posudbe', models.DateTimeField(auto_now_add=True)),
                ('datum_povrata', models.DateTimeField(blank=True, null=True)),
                ('je_vraceno', models.BooleanField(default=False)),
                ('knjiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posudba_knjige', to='knjiznica.knjiga')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posudba_korisnika', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('je_zaposlenik', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
