# Generated by Django 6.0.5 on 2026-05-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knjiznica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knjiga',
            name='puta_posudjena',
            field=models.IntegerField(default=0),
        ),
    ]
