# Generated by Django 6.0.5 on 2026-05-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knjiznica', '0002_knjiga_puta_posudjena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posudba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_posudbe', models.DateTimeField(auto_now_add=True)),
                ('datum_povrata', models.DateTimeField(blank=True, null=True)),
                ('je_vraceno', models.BooleanField(default=False)),
                ('knjiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posudba_knjige', to=settings.AUTH_USER_MODEL)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posudba_korisnika', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
