# Generated by Django 6.0.5 on 2026-05-16 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knjiznica', '0003_posudba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posudba',
            name='knjiga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posudba_knjige', to='knjiznica.knjiga'),
        ),
    ]
